sudo: required
services:
    - docker

before_install:
    - docker build -t mgulius90/docker-react -f Dockerfile.dev .
#conviene poner el nombre del repositorio GIT por un tema de convencion, sino poner otro nombre

script:
    - docker run mgulius90/docker-react npm run test -- --coverage
    